"""Initial migrations

Revision ID: 4ea1a0f156f4
Revises: 
Create Date: 2026-07-13 01:05:53.260603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ea1a0f156f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('events_generated', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_indicators',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('indicator_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_indicators_indicator_type'), 'threat_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_indicators_value'), 'threat_indicators', ['value'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('threat_narrative', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('predicted_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mitre_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('incident_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_incident_id'), 'incident_reports', ['incident_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('process', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=20), nullable=True),
    sa.Column('mitre_technique_name', sa.String(length=255), nullable=True),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_org_timestamp', 'security_events', ['organization_id', 'timestamp'], unique=False)
    op.create_index('idx_events_severity_timestamp', 'security_events', ['severity', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_hostname'), 'security_events', ['hostname'], unique=False)
    op.create_index(op.f('ix_security_events_incident_id'), 'security_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_security_events_organization_id'), 'security_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_user'), 'security_events', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_user'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_organization_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_incident_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_hostname'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index('idx_events_severity_timestamp', table_name='security_events')
    op.drop_index('idx_events_org_timestamp', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_incident_reports_incident_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_threat_indicators_value'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_indicator_type'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    op.drop_table('simulation_runs')
    op.drop_table('organizations')
    # ### end Alembic commands ###
